- name: configure 2 tomcat instances
  template:
      src: templates/server.xml.j2
      dest: /etc/tomcat7/server.xml
      mode: 0644
  become: yes
  become_user: root

- name: copy petstore to remote location
  copy: src=resources/petstore.tar dest=/tmp/
  become: yes
  become_user: root

- name: Unarchive petstore.tar to remote machine
  unarchive:
    src: /tmp/petstore.tar
    dest: /var/lib/tomcat7/webapps/
    remote_src: yes
  become: yes
  become_user: root

- name: configure jk.conf
  template:
      src: templates/jk.conf.j2
      dest: /etc/apache2/mods-enabled/jk.conf
      mode: 0644
  become: yes
  become_user: root

- name: configure worker.properties
  template:
      src: templates/worker.properties.j2
      dest: /etc/libapache2-mod-jk/workers.properties
      mode: 0644
  become: yes
  become_user: root

- name: configure 000-default.conf
  template:
      src: templates/000-default.conf.j2
      dest: /etc/apache2/sites-available/000-default.conf
      mode: 0644
  become: yes
  become_user: root

- name: install proxy
  command: a2enmod proxy
  become: yes
  become_user: root

- name: install http-proxy
  command: a2enmod proxy_http
  become: yes
  become_user: root

- service:
    name: tomcat7
    state: restarted
  become: yes
  become_user: root
  tags: start

- service:
    name: apache2
    state: restarted
  become: yes
  become_user: root
  tags: start